### PR TITLE
Enabled empty responses

### PR DESCRIPTION
**Pull request by tsndr**
If a zone exists but no records was set, it will always respond the SOA record, which is (compared to bind) the wrong behaviour. So i would push this answer instead:
```
res.answer.push({ name: question.name, type: question.type, data: null });
```
With my changes it's possible to return an empty response if the `data` attribute is set to `null`.
I hope its helpful 😊

### CODE REVIEW

**Comment by fogs** [comment]
Hi tsndr, 

It is helpful. 

Please keep in mind that the DNS protocol has a special flag (NXDOMAIN) that must be set for empty responses.

I have had the same issue 2 years ago, see #5 but this project is not maintained any more. 

Cheers, fogs

**Comment by tsndr** [comment]
Hi fogs,

thanks for the answer 😊

What do you think about a nodejs bade dns server in general? Only for testing or production ready? And what about the performance compared to bind, could it ever hold up?

Cheers,
Tobi 😊

**Comment by fogs** [comment]
If you are interested in availability, scalability, security, then choose one of the big and mature servers. PowerDNS rocks. If you like to play with the protocol, use it for stuff it was never intended to and don't think it hurts to learn more about DNS, there is no better way than building your own. We did both.

Cheers mate!

**Comment by fogs** [comment]
Ach. Und Grüße nach Remagen.

**Comment by tsndr** [comment]
I've never heard of PowerDNS, I might look into that 😊
I am using bind right now, but maybe I'll switch, we'll see 😉

Viele Grüße nach Hamburg 😊

**Pull request closed without merging**
